### ISSUE TITLE
FIX: Vue HTML template syntax highlighting breaks if attribute contains an arrow function 

### ISSUE THREAD

**Issue by jonowells** [tommasongr/nova-vue#10]
There is one case that is breaking the syntax highlighting. If a vue attribute contains an arrow function such as `<div @click="() => handleEvent"` the following tags all lose their syntax highlighting.

<img width="178" alt="Screen Shot 2020-10-30 at 10 41 45 AM" src="https://user-images.githubusercontent.com/500474/97719081-0e7a0f00-1a9d-11eb-9ed7-152bd79360f2.png">

<img width="253" alt="Screen Shot 2020-10-30 at 10 42 04 AM" src="https://user-images.githubusercontent.com/500474/97719096-120d9600-1a9d-11eb-9c20-e1f623780c76.png">

<img width="310" alt="Screen Shot 2020-10-30 at 10 42 11 AM" src="https://user-images.githubusercontent.com/500474/97719107-15a11d00-1a9d-11eb-9fe6-a16d027b7216.png">

I thought it might be related to the `>` appearing in the attribute, but it only seems to happen if there is a `=>` in the attribute somewhere other than the very beginning of the attribute, which I assume means it is specifically related to arrow function scope and not just the `=>` characters itself.

**Comment by tommasongr** [comment]
Nice catch! I'll take a look asap

**Comment by tommasongr** [comment]
@jonowells It has been pretty easy to fix. I just pushed an update. Let me know if it works. Thanks
