### ISSUE TITLE
Support pug language

### ISSUE THREAD

**Issue by tremendus** [tommasongr/nova-vue#13]
I see from the docs that you're waiting on pug language support. Locally I started migrating the pug regexes from the Atom extension ... and in a plain pug file the highlighting is starting to take shape - at least for the common features.

However, it doesn't work when `<template lang="pug"></template>` in a Vue single file component. 

I would have thought that your extension would have 'delegated' the language definition (braces/brackets, indents etc) and highlighting to the pug definition, but it seems not.

Any guidance in getting that to work would be appreciated.

**Comment by tommasongr** [comment]
Hi @tremendus happy to see that finally someone is tackling this! You are right the Vue extension should delegate your extension for displaying the syntax, my fault if that is not already in place. It will be pretty easy to implement but here is late night, I'll look at it tomorrow.

Is your extension already available? In the mean time if you want to send me over an example of Vue component using pug it would be useful for testing, thanks.

**Comment by tremendus** [comment]
I don't have an extension available - I simply took the 'slim' language definition which has a similar syntax, and created a local extension from it, changing the minimum necessary fields in the config xml to make it respond to pug files. 

I figure that between that and Atom's pug language definition, I should have most of what I need to get the core syntax def working for pug in Nova - syntax highlighting, indents, brackets and a few core pug features - keywords like include, require,  if/else for, etc .... if I could get that far, I'd publish and let others contribute on less-commonly used pug features, but I'm not there yet. 

Most of my work is in vue, so that's why I reached out - wasn't sure if it was me or the Vue extension not passing to the pug definition, which if I read the docs right is I *think* how it's suppose to work.

**Comment by tommasongr** [comment]
Could you upload it at least on github so I can activate it locally and perform some test?

**Comment by tremendus** [comment]
Ok, I'll either make it stable and upload it or I'll take a look at your VueHTML thanks.

**Comment by tremendus** [comment]
Ok, well I didn't quite get to it ... but this guy did. Love it if you could integrate yours with his extension.

[https://github.com/kpmcguire/nova-pug-syntax](https://github.com/kpmcguire/nova-pug-syntax)

**Comment by tommasongr** [comment]
Hi there! Sorry for the late reply.

Thats on my radar but unfortunately I've been a bit busy these days. I'll try to implement it asap

**Comment by tommasongr** [comment]
Hi just released an update with pug syntax support. Let me know how it is. Unfortunately the syntax definition is pretty poor and I haven't been able to define v-directives and other vue stuff, so you won't have access to all the completions and other rich features coming from the LSP

**Comment by tremendus** [comment]
Thanks. Yes I am seeing issues with the language definitions too. I'm just wrapping up a project that has to ship next week, when that's done, I'll take another look at my own language file for pug and continue migrating the Atom extension pug configs into it.
