### ISSUE TITLE
Compatibility with Nova 4

### ISSUE THREAD

**Issue by rijkvanzanten** [tommasongr/nova-vue#19]
Heya! 

I'm seeing some weird behavior when using this extension with Nova 4. The syntax highlighting only seems to work occasionally for TS, and not at all for CSS 🤔 

![CleanShot 2021-01-11 at 17 29 55](https://user-images.githubusercontent.com/9141017/104245647-a21f7280-5432-11eb-9c6d-326433dcb18c.png)

![CleanShot 2021-01-11 at 17 30 04](https://user-images.githubusercontent.com/9141017/104245658-a8155380-5432-11eb-8139-e43a5719147b.png)

I've reported this to Panic as well [through twitter](https://twitter.com/rijkvanzanten/status/1348732714556518401) though I'm not sure if it's a known breaking change in Nova, or a bug in the extension 🙂

**Comment by tommasongr** [comment]
Mmm that's weird...

I've updated to Nova 4 yesterday evening but I haven't been able to test different projects yet.

Can you send me the files that you have found broken?? That would be helpful.

Unfortunately this week I'm already a bit busy, I'll try to give it a look but I can't assure a patch until the weekend 😕

Thanks for the catch anyway 😉

**Comment by fosterdouglas** [comment]
Experiencing the same as OP, with my SFC .vue files. 

<img width="508" alt="Screen Shot 2021-01-12 at 4 35 54 AM" src="https://user-images.githubusercontent.com/7971443/104315460-d412f200-548f-11eb-9e56-b59156d713f0.png">

Otherwise, thank you for the great extension!

**Comment by rijkvanzanten** [comment]
> Can you send me the files that you have found broken??

@tommasongr Seems to happen on any Vue file for me 🤔 

For example [the basic Vue SFC](https://codesandbox.io/s/github/vuejs/vuejs.org/tree/master/src/v2/examples/vue-20-single-file-components) example from [the Vue docs](https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns):

```vue
<template>
  <p>{{ greeting }} World!</p>
</template>

<script>
module.exports = {
  data: function() {
    return {
      greeting: "Hello"
    };
  }
};
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
```

![CleanShot 2021-01-12 at 09 34 29](https://user-images.githubusercontent.com/9141017/104328012-6085da80-54b9-11eb-9541-9b11ad16a65d.png)

---

The weird thing is that TS seems to "kick in" after ~20 lines or so 

![CleanShot 2021-01-12 at 09 38 13](https://user-images.githubusercontent.com/9141017/104328572-f3bf1000-54b9-11eb-9a89-272da47a0f51.png)

**Comment by rijkvanzanten** [comment]
> Unfortunately this week I'm already a bit busy, I'll try to give it a look but I can't assure a patch until the weekend 😕

No problem! We're all familiar with open-sourcing next to actual life and jobs 🙂 In the meantime, is there anything I can do to help debug this?

**Comment by tommasongr** [comment]
Okk I've seen it now... it seems to be on every vue file... I think I'll try to give it a look now hoping can be fixed quickly.

In the meantime, thank you all guys! This is my first o.s. project and its quite fun to see you all interested in it! 😆

**Comment by rijkvanzanten** [comment]
> This is my first o.s. project and its quite fun to see you all interested in it!

Welcome to OSS! It's great ❤️ 

Always fun to know by who/where your software is used. In this case, your project is directly helping the development of [Directus](https://github.com/directus/directus) 😉

**Comment by tommasongr** [comment]
Okk folks, I've found the problem.

This is the markup I was using for the standard script block. Every other block (ts, coffeescript, css, sass...) is just I modified version of this very one.
```xml
<scope name="vue.embedded.block.script" spell-check="false" lookup="documentation">
      <starts-with>
	      <expression>(?=&lt;(?i:script)\b)</expression>
      </starts-with>
      <ends-with />
      <subscopes anchored="true" skip-whitespace="false">
	      <scope name="vue.tag.script.open">
		      <symbol type="tag-script">
			      <display-name>
				      <component variable="name" />
				      <component selector="vue.tag.attribute.value.link" prepend=" – " />
			      </display-name>
			      <context behavior="start" group-by-name="true">
				      <auto-close string="&lt;/" completion="${name}&gt;" />
			      </context>
		      </symbol>
		      <starts-with>
			      <expression>&lt;((?i:script))</expression>
			      <capture number="1" name="vue.tag.name" />
		      </starts-with>
		      <ends-with>
			      <expression>/?&gt;</expression>
		      </ends-with>
		      <subscopes>
			      <include syntax="html" collection="attributes" />
		      </subscopes>
	      </scope>
	      <scope name="vue.embedded.block.script.content" optional="true">
		      <starts-with>
			      <expression>(?&lt;=&gt;)</expression>
		      </starts-with>
		      <ends-with>
			      <expression>(?=&lt;/(?i:script)\b)</expression>
		      </ends-with>
		      <subsyntax name="javascript">
			      <cut-off>
				      <expression>(?=&lt;/(?i:script)\b)</expression>
			      </cut-off>
		      </subsyntax>
	      </scope>
      </subscopes>
</scope>
```

I looked at the html extension bundled with Nova and this is their implementation of the script tag in html (which is also where I took the previous one).
```xml
<scope name="html.embedded.script" spell-check="false" lookup="documentation">
      <starts-with>
          <expression>(?=&lt;(?i:script)\b)</expression>
      </starts-with>
      <ends-with />
      <subscopes anchored="true" skip-whitespace="false">
          <scope name="html.tag.script.open">
              <symbol type="tag-script">
                  <display-name>
                      <component variable="name" />
                      <component selector="html.tag.attribute.value.link" prepend=" – " />
                  </display-name>
                  <context behavior="start" group-by-name="true">
                      <auto-close string="&lt;/" completion="${name}&gt;" />
                  </context>
              </symbol>
              <starts-with>
                  <expression>&lt;((?i:script))</expression>
                  <capture number="1" name="html.tag.name" />
              </starts-with>
              <ends-with>
                  <expression>/?&gt;</expression>
              </ends-with>
              <subscopes>
                  <include syntax="self" collection="attributes" />
              </subscopes>
          </scope>
          <scope name="html.embedded.script.content" optional="true">
              <starts-with>
                  <expression>(?&lt;=&gt;)</expression>
              </starts-with>
              <ends-with>
                  <expression>(?=&lt;/(?i:script)\b)</expression>
              </ends-with>
              <subsyntax name="javascript">
                  <cut-off>
                      <expression>(?=&lt;/(?i:script|head|body|div)\b)</expression>
                  </cut-off>
              </subsyntax>
          </scope>
      </subscopes>
</scope>
```

As you can see they removed the first ends-with and used a shorthand `<ends-with />` and add a couple of attributes to the subscopes `<subscopes anchored="true" skip-whitespace="false">`

I added these two changes and the script tag works now!
<img width="455" alt="Schermata 2021-01-12 alle 16 26 57" src="https://user-images.githubusercontent.com/25225746/104334726-03a71600-54f3-11eb-8768-c6f2964a76a5.png">

I'll do the same for every other block and finger cross I'll push an update in half an hour!

**Comment by fosterdouglas** [comment]
> I'll do the same for every other block and finger cross I'll push an update in half an hour!

Wow, that's some speedy service... 👍

**Comment by rijkvanzanten** [comment]
I love the irony of this:

![CleanShot 2021-01-12 at 10 32 52](https://user-images.githubusercontent.com/9141017/104335682-9cbd3900-54c1-11eb-922c-97eeab214d8b.png)

Thanks a lot @tommasongr! ❤️

**Comment by rijkvanzanten** [comment]
Aaaaand we're back!

![CleanShot 2021-01-12 at 10 44 40](https://user-images.githubusercontent.com/9141017/104337191-346f5700-54c3-11eb-95ec-4de1ead9dcb2.png)

Thanks again @tommasongr ❤️

**Comment by tommasongr** [comment]
#20 This should solve it! I pushed the update, let me know if it works!

**Comment by tommasongr** [comment]
> Wow, that's some speedy service... 👍

hahaha particularly speedy beacuse without it today I wouldn't be able to work 😂

**Comment by jonathan-wondereur** [comment]
Thanks for the fast update!

**Comment by tommasongr** [comment]
Hi again! This is the last one for today ahahah. Since I've seen you engaged I opened this discussion #21 hoping for some feedback, feature ideas or suggestion. I would like to riceive some feedbacks particularly on the experience with typescript and vue 3.

Thank you all! 😉

**Comment by logancollins** [comment]
Just wanted to mention that I'm sorry that this happened! I didn't think our changes to the grammar format in Nova 4 would impact existing grammars like this. I will investigate to see why this might've changed, but I'm happy to hear you were so quickly able to apply a fix.

**Comment by tommasongr** [comment]
@logancollins don't worry, fortunately has been pretty easy to find the bug this time. Especially with the bundled extensions open to inspect, that has been pretty usefull in the past for the syntax stuff.

Anyway thanks for the overall great update! I've seen some good stuff about git, particularly the new history tab... I hope you will expand on it.

P.S: Any news about debugging features?? I friend of mine was considering making an extension for robot framework (testing stuff) that would need a debugger. Thanks

**Comment by logancollins** [comment]
Debugger support is actively being investigated. It won't arrive _soon_, as there's a lot of moving pieces to support it, but it is definitely something we're working towards. I'm hoping to have something to share on that stuff later this year.

**Comment by tommasongr** [comment]
Awesome!

Just one more thing... I'm a bit disappointed here... ahahhaha

There is for sure some caching problem here ahahah I tried everything except a fresh re-install... Any hints?

<img width="319" alt="Schermata 2021-01-12 alle 19 19 55" src="https://user-images.githubusercontent.com/25225746/104355759-686e6a80-550b-11eb-9a6b-f1bc8eb0906d.png">
<img width="461" alt="Schermata 2021-01-12 alle 19 19 44" src="https://user-images.githubusercontent.com/25225746/104355760-69070100-550b-11eb-98d4-5db7b43b7f3e.png">
