### ISSUE TITLE
Syntax highlighting breaks for self-closing tags

### ISSUE THREAD

**Issue by chriscalo** [tommasongr/nova-vue#23]
Thanks for the Vue extension for Nova!

I've noticed that the extension doesn't seem to work with self-closing tags in `.vue` files.

Syntax highlighting is correct without the self-closing slash:

![image](https://user-images.githubusercontent.com/867717/104677731-f25b3680-56b7-11eb-97ae-947f8931fe14.png)

As soon as you add the self-closing slash, things become miscolored:

![image](https://user-images.githubusercontent.com/867717/104677696-e1aac080-56b7-11eb-8e31-47135b812e4c.png)

Note this doesn't happen in HTML files in Nova:

![image](https://user-images.githubusercontent.com/867717/104677983-76152300-56b8-11eb-8243-8af602d7b397.png)

With a custom component with explicit closing tags, coloring is correct:

![image](https://user-images.githubusercontent.com/867717/104677839-26365c00-56b8-11eb-81e8-cc4acf9b9837.png)

As soon as you use a self-closing slash, things break again:

![image](https://user-images.githubusercontent.com/867717/104677902-49f9a200-56b8-11eb-983b-fcb65b4e4ba7.png)

**Comment by tommasongr** [comment]
Thanks for the catch! I'll take a look in the afternoon 😉

**Comment by tommasongr** [comment]
Hi there! I just released an update v3.2 which solves this issue. Thanks for your feedback! 😉

**Comment by chriscalo** [comment]
Syntax highlighting now works perfectly 👍

I did notice one more related issue where the symbol path at the top of an editor tab is incorrect:

![image](https://user-images.githubusercontent.com/867717/104824825-5cdcb580-5823-11eb-912f-7e8832737b94.png)

If I add a separate </Nav> closing tag, the symbol path is correct for this same cursor position:

![image](https://user-images.githubusercontent.com/867717/104824855-a5946e80-5823-11eb-9e2b-ff536bfc6fc9.png)


Would it be better if I file a separate issue for this?

**Comment by tommasongr** [comment]
Thanks! I don't use symbols usually so I've never noticed it. Thanks for the catch!

If you have time you can filed a new issue, otherwise don't worry 😉

**Comment by chriscalo** [comment]
Not hard at all, will copy to a new issue…
