### ISSUE TITLE
Incorrect eslint error message: [vue/no-multiple-template-root]

### ISSUE THREAD

**Issue by chriscalo** [tommasongr/nova-vue#25]
Generated a fresh Vue3 app via @vue/cli and seeing this eslint error:

![image](https://user-images.githubusercontent.com/867717/104959320-fa5cf400-599f-11eb-9923-55fa5ca386c1.png)

Vue3 [no longer](https://v3.vuejs.org/guide/migration/fragments.html) has the constraint of one root element in a component template.

I'd be happy with any of these fixes:
- making this rule smart enough to detect vue2 vs vue3 projects
- having eslint turned off by default (I never use eslint and can't find where to turn it off)
- a setting to turn off eslint in `.vue` files (this may exist, I just don't know how to do it)

**Comment by tommasongr** [comment]
Hi there! Sorry for the delay...

I've been able to refactor/improve a lot in the last weekend. With #29 the Vetur API is finally exposed in the extension preferences. You can finally tweak everything about code validation and much more.

Anyway I tested a vue3 project with the standard configuration and I don't see that error anymore. Probably has been solved by the Vetur team 🎉

<img width="470" alt="CleanShot 2021-05-03 at 11 24 48@2x" src="https://user-images.githubusercontent.com/25225746/116860890-8c60d380-ac02-11eb-91a8-763c34b13c90.png">

Let me known if everything works fine!

Enjoy

**Comment by chriscalo** [comment]
Perfect, thank you! 🙏 I found where to turn off validation in the extension settings 👍
