### ISSUE TITLE
Expose the Vetur API

### ISSUE THREAD

**Issue by felixqueisler** [tommasongr/nova-vue#26]
![Screenshot 2021-03-04 at 11 40 21](https://user-images.githubusercontent.com/3536483/109951893-87ed6c80-7cde-11eb-82df-9888ba35bffe.png)

Actually there is no problem but it'll still give you this error-warning in the editor.

How to fix: https://github.com/ionic-team/ionic-framework/issues/22236#issuecomment-731000931
I'm not aware of how I'd do that myself.

> I believe you're getting this issue because of the Vetur plugin, not ESLint.
> Turn off the Vetur setting "validate vue-html in <template> using eslint-plugin-vue" and you'll see your project abiding by your .eslintrc.js rules.

**Comment by tommasongr** [comment]
Hi there! Sorry but I'm not sure what do you want me to do. Are you asking how can you change the Vetur settings by your own?

In the mean time you can always disable that rule by placing this comment at the top of your file.
`<!-- eslint-disable vue/no-deprecated-slot-attribute -->`

Let me know, thanks

**Comment by felixqueisler** [comment]
Hey Tomasso,
I'm unfamiliar with Vetur. I figured the settings would be embedded in the extension and can't be edited by myself?
Thanks for the rule tip.

After some digging I found that slot is actually deprecated with vue 3. I thought it wasn't true.

**Comment by felixqueisler** [comment]
Nevermind. I'm running into this problem: https://ionicframework.com/docs/vue/troubleshooting#slot-attributes-are-deprecated ... it's mixing up web component slot with the vue slot. So it's not actually deprecated.

I was able to disable the error with placing `<!-- eslint-disable vue/no-deprecated-slot-attribute -->` **inside** the `<template>` tag.
Is this something which could get prevented extension-side?

**Comment by tommasongr** [comment]
I'm planning to catch up with all the open issues in the upcoming days, I'll try to look at this too.

I'm not sure if I would be able to expose the Vetur API because I'm not an expert of it too. I'll probably need some help but I'll see what I can do on my own.

**Comment by tommasongr** [comment]
I'll reopen the issue as Exposing the Vetur API

**Comment by tommasongr** [comment]
The Vetur API has been exposed with #29 🎉

Close the issue
