### ISSUE TITLE
Syntax highlighting broken by self-closing <style/> tag

### ISSUE THREAD

**Issue by chriscalo** [tommasongr/nova-vue#27]
Notice in the screenshot here that, following the self-closing `<style/>` tag, syntax highlighting for the `<template>` tag is broken. (This is valid syntax in `.vue` files.)

![image](https://user-images.githubusercontent.com/867717/110228357-78cd1100-7ece-11eb-83c6-bb6e33274244.png)

Everything looks correct if I add the closing `</style>` tag:

![image](https://user-images.githubusercontent.com/867717/110228404-d6f9f400-7ece-11eb-8ccb-988182bd6495.png)

**Comment by tommasongr** [comment]
Thanks for reporting this! I've been a bit busy lately but I'll try to fix this asap

**Comment by chriscalo** [comment]
(don't rush on my account, just trying to be helpful in filing bugs as I see them. thanks again for creating this plugin 🙏)

**Comment by tommasongr** [comment]
The new tree-sitter based syntax added in v7.0 solved the issue. Closing
