### ISSUE TITLE
Nova version 7 breaks the plugin

### ISSUE THREAD

**Issue by war1an** [tommasongr/nova-vue#34]
On a brand new project `vue create project_name`

If I try to delete the default styles inside App.vue... Nova crashes.

**Comment by tommasongr** [comment]
Hi there. I'm sorry you are experiencing this 😕. I hope you have found a workaround...

Unfortunately I was aware of this issue. I've never been able to identify the cause though. Technically the syntax implementation is right, probably there is a problem with Nova and how it andles multiple languages in the same file. Vue is a complex syntax in terms of sub-components, in fact I've seen it happen mostly when you delete a level 0 block like template, script or style.

**Comment by tommasongr** [comment]
Thanks to the good work of the folks at @panicinc Nova v7.2 solves this issue!
