### ISSUE TITLE
crash when editing .vue file with no style section

### ISSUE THREAD

**Issue by mlilback** [tommasongr/nova-vue#40]
1. Create a new .vue file. 
2. Type an empty template and script sections.
3. Start to type the style section and save it. The app will crash before you can save it.

A crash also happens if you paste the following and start to add the style tag:

```
<template>
	content
</template>

<script>
import { reactive, ref, onMounted, nextTick } from 'vue';

export default {
	name: 'Component',
	props: {
		modelValue: { type: String, required: true, },
	},
	setup(/* props, context */) {
		return {}
	}
};
</script>
```

[Nova_2021-07-14-194257_Wednesday.txt](https://github.com/tommasongr/nova-vue/files/6819454/Nova_2021-07-14-194257_Wednesday.txt)

**Comment by tommasongr** [comment]
Hi there, sorry for the late response.

This is a known issue... see #34

Unfortunately I think is something related to Nova and the fact that the Vue syntax is quite of an unusual one. My guess is that the syntax engine was not developed with the idea of having three different subsyntaxes in one file and when you remove one of them in a "weird" way it crashes

**Comment by tommasongr** [comment]
Thanks to the good work of the folks at @panicinc Nova v7.2 solves this issue!
