### ISSUE TITLE
Support for Volar

### ISSUE THREAD

**Issue by P4sca1** [tommasongr/nova-vue#44]
From https://vuejs.org/guide/typescript/overview.html#ide-support:
> Volar replaces [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur), our previous official VSCode extension for Vue 2. If you have Vetur currently installed, make sure to disable it in Vue 3 projects.

Volar also has experimental support for Vue.js 2 projects. 
Maybe a setting could be provided, which language server should be used?

**Comment by tommasongr** [comment]
Hi there! Sorry for the late reply.

I just wanted to let you know that I'm starting looking at Volar and at the shift from Vetur. I'm not sure I will end up leaving both Volar and Vetur as possible options. I'm worried it might end up messing up the code.

The possible solution I'm considering are:
- Creating a new extension with the legacy Vetur version and moving this one to Volar
- Leaving this extension just for Vue syntax and creating two new extension for the language servers

I would really like to get some feedback and ideas around this shift. So please let me know your thoughts.

Thanks!

**Comment by tommasongr** [comment]
v6.0 comes with Volar support!

Check out the README for the new required installation process for both Volar and Vetur.

😉
