### ISSUE TITLE
Extension only partially working

### ISSUE THREAD

**Issue by GaryREM** [tommasongr/nova-vue#53]
I have installed extension and am pointing to project specific instances of the Volar languages server and Typescript libraries:

```
 /Users/grmensz/Documents/MySites/vuecourse-max/main-prj/node_modules/@volar/vue-language-server

 /Users/grmensz/Documents/MySites/vuecourse-max/main-prj/node_modules/typescript/lib/tsserverlibrary.js
```
The highlighting appears on vue files.
The 2 vue clips show up.
There is no autocompletion in template section of vue files.
There is no autocompletion in script section of vue files.
There IS autocompletion in style section.

There is no Vue extension entry in the Nova extension menu.

I see 2 entries for Vue in the Extension console:

```
Hello from Vue 💎

Encountered a zero-length single match for scope: <SKScope: 0x600002941130 : name=css.style.string.double-quoted.path, type=Match, regex=<SKRegularExpression: 0x60000064d780> { pattern=(?:[^"\\]|\\.)*, options=82 }, endRegex=(null)>; Ignoring
```

Any hints on what is wrong?

Note I am running macOS 13.
I am running the following extensions:
HTML Snippets
HTML Validator
Markdown Clips
Prettier
Typescript
Vue

Thanks...

**Comment by GaryREM** [comment]
resolved this by:

1. adding jsconfig.json with section "jsx": "preserve" under compilerOptions
2. installed version 0.40.4 of Solar language server

**Comment by johnsoncodehk** [comment]
Please track #54

**Comment by GaryREM** [comment]
Upgraded to Volar 1.0.16.
No jsconfig file.
Commented out languageFeatures and documentFeatures in VolarLangugeServer.js in extension.
Modified typescript property:
```
typescript: {
          tsdk: "/usr/local/lib/node_modules/typescript/lib",
          // serverPath: typescriptPath,
        },
```

All is working.

**Comment by peterkos** [comment]
As an alternative workaround, #55 worked for me
