### ISSUE TITLE
Typescript not working due to vue-language-server error

### ISSUE THREAD

**Issue by cabeeb** [tommasongr/nova-vue#55]
I haven't been able to get Typescript working in Vue SFCs. Autocomplete and syntax highlighting work great, but no TS. When I look in the extension console, I see this error:
```-32603 Request textDocument/codeAction failed with message: host.getVueCompilationSettings is not a function```

I've tried reinstalling @volar/vue-language-server globally, installing it to the project, specifying absolute paths to both global and project installations, but it always gives the same error. I also tried uninstalling the plugin and reinstalling, but no luck. Any guidance would be greatly appreciated!

**Comment by cabeeb** [comment]
Follow-up: I installed `@volar/vue-language-server@0.40.13` (the last version before 1.0.0 was released last October) and it works fine, so I'm assuming it's a breaking change that hasn't been accounted for in this package. Easy enough to workaround in the meantime 👍

**Comment by johnsoncodehk** [comment]
Please wait for #54.
